# Generated by Django 5.0.7 on 2024-08-01 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("main_description", models.TextField()),
                ("image", models.FileField(blank=True, upload_to="project_images/")),
                ("order", models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Project_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("code", models.TextField(blank=True)),
                ("image", models.FileField(blank=True, upload_to="project_images/")),
                (
                    "sk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
